# Generated by Django 6.0.6 on 2026-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('uploadedFile', models.FileField(upload_to='%Y/%m/')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
